/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdditionalSecurity: typeof import('./src/components/CreatePassword/AdditionalSecurity.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    Cart: typeof import('./src/components/Cart.vue')['default']
    ChickenBiryani: typeof import('./src/components/home/chicken-biryani.vue')['default']
    Commercial: typeof import('./src/components/Commercial.vue')['default']
    DeliveryBiryani: typeof import('./src/components/home/delivery-biryani.vue')['default']
    DesktopView: typeof import('./src/components/DesktopView/DesktopView.vue')['default']
    ExploreOurMenu: typeof import('./src/components/home/explore-our-menu.vue')['default']
    ExploreOurMenuList: typeof import('./src/components/home/explore-our-menu-list.vue')['default']
    Featured: typeof import('./src/components/MobileView/Featured/Featured.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterMobile: typeof import('./src/components/FooterMobile.vue')['default']
    Grid: typeof import('./src/components/DesktopView/Happening/partials/grid.vue')['default']
    GridCard: typeof import('./src/components/GridCard.vue')['default']
    Happening: typeof import('./src/components/DesktopView/Happening/Happening.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageCropperDialog: typeof import('./src/components/ImageCropperDialog.vue')['default']
    LambBiryani: typeof import('./src/components/home/lamb-biryani.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MainLogo: typeof import('./src/components/mainLogo.vue')['default']
    MenuCard: typeof import('./src/components/home/partials/menu-card.vue')['default']
    MobileView: typeof import('./src/components/MobileView/MobileView.vue')['default']
    MuttonBiryani: typeof import('./src/components/home/mutton-biryani.vue')['default']
    OtherPromotion: typeof import('./src/components/MobileView/Promotions/OtherPromotion/OtherPromotion.vue')['default']
    OTPEmail: typeof import('./src/components/SignUpEmail/OTPEmail.vue')['default']
    Partners: typeof import('./src/components/Partners.vue')['default']
    PersonalDetailEmail: typeof import('./src/components/SignUpEmail/PersonalDetailEmail.vue')['default']
    PersonalDetailMobile: typeof import('./src/components/SignUpMobile/PersonalDetailMobile.vue')['default']
    PersonalDetailSocials: typeof import('./src/components/SignUp/PersonalDetailSocials.vue')['default']
    PrawnBiryani: typeof import('./src/components/home/prawn-biryani.vue')['default']
    Promotions: typeof import('./src/components/MobileView/Promotions/Promotions.vue')['default']
    PropertyCard: typeof import('./src/components/PropertyCard.vue')['default']
    Residential: typeof import('./src/components/Residential.vue')['default']
    RestaurantDish: typeof import('./src/components/home/restaurant-dish.vue')['default']
    RestaurantServing: typeof import('./src/components/home/restaurant-serving.vue')['default']
    ResultRegister: typeof import('./src/components/CreatePassword/ResultRegister.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServingCard: typeof import('./src/components/home/partials/serving-card.vue')['default']
    VegBiryani: typeof import('./src/components/home/veg-biryani.vue')['default']
    Welcome: typeof import('./src/components/SignUp/Welcome.vue')['default']
    YourOrder: typeof import('./src/components/YourOrder.vue')['default']
  }
}
